### ISSUE TITLE
Usage with bistable relays

### ISSUE THREAD

**Issue by Misiu** [jpcornil-git/RPiHat_GPIO_Expander#1]
Hi there,

would it be possible to use your board with bistable relays?
my idea is to have lights in room controlled by a bistable relay. The light will be turned on/off by momentary switches around the room (that's the standard usage).
I'd like to plug home assistant to this, so I'll be able to read the state of the relay (is the light on or off) and also change the state (via the web interface)
The idea is to have lights function normally even when automation (raspberry pi with Home Assistant) is down.

**Comment by jpcornil-git** [comment]
Sure, you can use the board to control a bistable relay (it would be placed in // with the existing push button) but you will need some additional circuitry to read the state of the relay.

If you goal is to have a system running independently of RPi/HA, you may want to consider KNX devices for switches & button sensors and use HA to address automation/mobile interface/... (HA supports KNX integration)
 
Cheers
jpc

**Comment by Misiu** [comment]
@jpcornil-git thanks for the reply.
I was looking at KNX but it is very expensive.
In my case, I want to control 12 lights in my house. Bistable relay is ideal, but I need a way to control it from Home Assistant.
I was looking at Shelly devices, but I'd like to avoid wireless communication.
I found this tutorial: https://www.instructables.com/id/Latching-Relay-Module/ but I want to avoid building such modules.

Ideally, I'd like to use two of your expansion boards to control and read up to 16 lights.
I must search for din rail relays that do what I need. The problem is I don't know if such a device exists :D

I'll update you if I find something useful.

**Comment by jpcornil-git** [comment]
You don't have to build custom modules for this, there are standard DIN rail solutions for set/reset relays , e.g.  with 24VDC coil https://www.tme.eu/ch/fr/details/13.12.0.024.0000/relais-dinstallation/finder/ (there are much more products with a singe coil/push-button)

Cost of 16x of theses relais is comparable to a KNX 16p switch e.g. https://www.eibabo.be/fr/gira/dispositif-d-e-s-combine-pour-knx-maisons-et-batiments-intelligents-automation-103800-eb10828887?fs=1183920387

Of course, with  KNX, you need to add (the cost of) a KNX interface for each push button and an IP gateway (~100EUR) to enable communication with HA.

Cheers
jpc

**Comment by jpcornil-git** [comment]
No further question/feedbacks -> closing the case
